### ISSUE TITLE
Examples Won't Compile

### ISSUE THREAD

**Issue by NoahMarconi** [vyper-online/editor#11]
https://vyper.online/

Simple Open Auction gives this error `map expects one arg (the type)`

On Chain Market Maker gives this error `line 1: Invalid top-level statement
from vyper.interfaces import ERC20`

Others give different errors. None of the built in examples compile, however.

**Comment by SilentCicero** [comment]
Yeah, I get this as well. Pretty sad, considering I was going to use the language :(

**Comment by NoahMarconi** [comment]
> Yeah, I get this as well. Pretty sad, considering I was going to use the language :(

Don't let the online editor deter you. The `pip` package and `docker` based compilers both work fine.

https://vyper.readthedocs.io/en/latest/installing-vyper.html#pip

**Comment by holgerd77** [comment]
Sorry for the delay, have partly fixed this. The auto-update broke at some point in time during some changes on the ``vyper`` repo. ``ABI`` and ``LLL`` code generation are now working again.

For the ``Bytecode`` tab I have the following error:

```
module 'vyper.compiler' has no attribute 'compile'
```

This sounds like something in the internal module structure changed. Would be glad if someone could give me a hint.

//cc @fubuloubu

**Comment by fubuloubu** [comment]
It has. We reconfigured the compiler API so it's no possible to get all of those things out at once from the python module directly. There's some new features and functionality in the API as well, like multiple file support.

Also, @jacqueswww maintains remix.vyper.live, which is a port of remix online editor with the Vyper plugin installed. I think the main remix.ethereum.org has this plugin under experimental features, so that might be another option moving forwards. vyper.online has been really great for us, but it might be time to sunset with the upgrade available on remix?

**Comment by holgerd77** [comment]
@fubuloubu Ah, see.

I've no problems with sunsetting if the time is there. I think vyper.online might generally be a lot more approachable for people with its current simplicity than directly have to digging through Remix with all its complexity?

**Comment by fubuloubu** [comment]
Yeah, I agree. It's always been helpful to me just to see if some examples compile or not. Are you running any sort of analytics on the web traffic? I guess we should try and figure out if a lot of people are using it before making such a decision.

**Comment by holgerd77** [comment]
Just had a look, roughly 200-300 users/months. Not sure what you would make of these numbers?

**Comment by fubuloubu** [comment]
That's... Unexpectedly good! I guess let's fix it and keep it running? If you need any help, hit me up on gitter!

**Comment by holgerd77** [comment]
If you can give me a link to the compiler API changes (out of lazyness 😄) that would be helpful!

**Comment by fubuloubu** [comment]
Updates occured here: https://github.com/ethereum/vyper/pull/1089

**Comment by holgerd77** [comment]
Ok, should be working again, changed ``bytecode = '0x' + compiler.compile(source).hex()`` to ``bytecode = compiler.compile_code(source)['bytecode']``, see the respective [commit](https://github.com/vyper-online/api/commit/e51f13ce315b9a5e0a6fccdcea9bad85e1967c44).

**Comment by holgerd77** [comment]
Also updated the examples, all examples are compiling:
https://vyper.online/

Will close here.

**Comment by holgerd77** [comment]
@fubuloubu For these two things (API changes on your side, example additions or changes) it would actually be great if you think of dropping me a note so that I can update. I am just too far off atm and won't find time to follow chats or the like.

**Comment by fubuloubu** [comment]
Shouldn't have to update it again, we just wanted to change the API so you could get all the outputs at the same time.
